{% set version = '0.27' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgmaker
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgmaker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgmaker/pkgmaker_{{ version }}.tar.gz
  sha256: 17a289d8f596ba5637b07077b3bff22411a2c2263c0b7de59fe848666555ec6a

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: devtools (>= 0.8), roxygen2, RUnit, testthat, knitr, rmarkdown, yaml, Biobase
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bibtex >=0.4
    - r-codetools
    - r-digest
    - r-magrittr
    - r-registry
    - r-stringi
    - r-stringr
    - r-withr
    - r-xtable

  run:
    - r-base
    - r-bibtex >=0.4
    - r-codetools
    - r-digest
    - r-magrittr
    - r-registry
    - r-stringi
    - r-stringr
    - r-withr
    - r-xtable

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pkgmaker')"           # [not win]
    - "\"%R%\" -e \"library('pkgmaker')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://renozao.github.io/pkgmaker
  license: GPL (>= 2)
  summary: Provides some low-level utilities to use for package development. It currently provides
    managers for multiple package specific options and registries, vignette, unit test
    and bibtex related utilities. It serves as a base package for packages like NMF,
    RcppOctave, doRNG, and as an incubator package for other general purposes utilities,
    that will eventually be packaged separately. It is still under heavy development
    and changes in the interface(s) are more than likely to happen.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: pkgmaker
# Type: Package
# Title: Development Utilities for R Packages
# Version: 0.27
# Date: 2018-05-25
# Authors@R: person("Renaud", "Gaujoux", email = "renozao@protonmail.com", role = c("aut", "cre"))
# Description: Provides some low-level utilities to use for package development. It currently provides managers for multiple package specific options and registries, vignette, unit test and bibtex related utilities. It serves as a base package for packages like NMF, RcppOctave, doRNG, and as an incubator package for other general purposes utilities, that will eventually be packaged separately. It is still under heavy development and changes in the interface(s) are more than likely to happen.
# License: GPL (>= 2)
# URL: https://renozao.github.io/pkgmaker
# BugReports: http://github.com/renozao/pkgmaker/issues
# LazyLoad: yes
# Encoding: UTF-8
# Depends: R (>= 3.0.0), methods, stats, registry
# Imports: tools, grDevices, utils, graphics, codetools, digest, stringi, magrittr, stringr, xtable, withr, bibtex (>= 0.4)
# Suggests: devtools (>= 0.8), roxygen2, RUnit, testthat, knitr, rmarkdown, yaml, Biobase
# Collate: 'bibtex.R' 'colors.R' 'data.R' 'namespace.R' 'utils.R' 'devutils.R' 'files.R' 'graphics.R' 'options.R' 'logging.R' 'unitTests.R' 'is.R' 'knitr.R' 'registry.R' 'package-extra.R' 'package.R' 'packages.R' 'project.R' 'rd.R' 'user.R' 'vignette.R' 'with.r'
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-05-25 21:48:47 UTC; renaud
# Author: Renaud Gaujoux [aut, cre]
# Maintainer: Renaud Gaujoux <renozao@protonmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-25 22:18:01 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
