travis:
  secure:
    BINSTAR_TOKEN: ZWRJy/TvrE5JV65aORspKY6bsNBqwR6lcbKEu5Crlv2qwRY2PCimbS+enGb6ez84zMf7y50puOZkBJE2ANN8hssKpq4jOcJEOPoCnAUX5sc4jNYsqHXNF/fbZ/KTVDvEoXWQv1TqBMemszpItnl0FqXGZnT+uwmJh2XnSAzbyhfXHG9e9zTPXKmatQIodh0jkpN9+jyJM4xyieE1wH+7zOWlrG67UYi0lKCBpCitd1cCvTZFdZYcOdPmtZBmHcfgUTPYOWlRNN8h23eMKe3c4zVaHDP+43gDiExD+bQ9dS5gSJLe5BNeE8n0MsoMsb/DxIKoNRXLNEsn4ElbR0pLxv0ARNt/AkDckSO0TXSCCFqm4hfgEN4NoDfkR6Zn3PBQaQM1IUtU//GNzhMkp9aAoNyzwTQTIAGaRQFB3BRq8oNAPEBdWn+qdnZrkjDBYYHgpNUvvXYtVPN/eAG6flZT5BoIVLnOGqL7t1zERUhFfaxUobPUtP5Aemp8h73KOaDWv1NDa/mF1ECsYxQl6ezITUybFNY41+EMNsgC50BHHR5qr5ujXvegI6Vdj4sUhmya69sd5kfF9NaPahlhNFqu2q7IlqqGlI0OgHN++rqxiCfKeRwSZrGtM+oWUP7yjkAj+A62UkXyloWc338K6WHx6INJic2HX+PvCTypDM1k5JM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
