travis:
  secure:
    BINSTAR_TOKEN: IK3iIkLiXUtR7dLuVh/rNq4CbgCyDoEi2irR3h2Gk6e5lQhUkaCD/tF1E9yXto0YKvtJYdX088sIEw3MAdk9eDjnNTvmW8DQWm+6d7zk7R1FwCgeeRkG0+gRRYOA18TuRlcVsnojQdte+mq/PzO6clON/EOyhF3giXRakFU+ETG3V/DUnuUUT42RYGbE4S6pTlPwXmNpHVer9ov2weXLjXH1GOnvdK5Jc7mgjcEaqTPi+8W4+UV73UswoYZqtjlpnqI37FiDRiSbSWG8vK4SpBmjHULYG6IclI74W/7kf2lvRZxfcy77td3pk6BEpgoQk3Y3zxeiroLLwPFjRck+jr6I8i6NfLHRfm77/ZI77YdzIp+7wtlolS14HeZtakxTWGruYyHHobSGXoTExno9aO0MuvLr2znHMLWUwEXlMrkrUP60VnN/lQ1v3pXbx9S3DBj2kTyHtB+scdJjcOP2FjnAiLpxyEES2010zGDUHrIxRi7PWDRRFQI/GkMeOcPRiAqOLo3OHI5wVMnbc3JY2Sn548ZOtV03Uw+UvYXzeYm2cjBVb8AQe/9K+xQGgsU87nAuYImZEKqB4DXfAuNHRYK3xxeGj560RG2QBKD0nIcK8NlPgVDSjeRNE5b6ITVFO4/9GXQrloxqC1C6Q3/cokatIBZp1MBEVYmYDdsVR34=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
